node {
  
  stage('GIT CheckOut') {
    git branch: 'development ', url: 'https://github.com/amitvashisttech/mindtree-devops-27April2020.git'
  }

  def project_path = "petclinic-code"
  
  dir(project_path) {

  stage('Maven-Clean') {
    sh label: '', script: 'mvn clean'
  }

  stage('Maven-Compile') {
    sh label: '', script: 'mvn compile'
  }
  
  stage('Maven-Test') {
    sh label: '', script: 'mvn test'
  }
  
  stage('Maven-Package') {
    sh label: '', script: 'mvn package'
  }

  stage('Stage Deployment- Env Docker') {
    sh label: '', script: 'docker-compose up -d --build'
  }
 }
}
